backend:
  name: github
  branch: main
  repo: Nonbinary-Hebrew-Project/website

# These lines should *not* be indented
media_folder: "docusaurus/static/img"
public_folder: "/img/"

collections:
  - name: about
    label: "about us"
    folder: docusaurus/src/pages/about
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: false
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-lin hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }

  - name: grammar
    label: "Grammar"
    folder: docusaurus/docs
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-lin hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }
      - { name: slug, label: Slug, widget: string }
      - {
          name: sidebar_position,
          label: "Sidebar Position",
          widget: number,
          value_type: int,
        }
  - name: blog
    label: "Applied Uses"
    folder: docusaurus/blog
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-lin hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }
      - {
          label: "PDF File",
          name: "pdf_file",
          widget: "file",
          required: false,
          media_library: { config: { multiple: false } },
          hint: "Only add PDF-type files. Use <PdfViewer frontMatter={frontMatter} /> to embed the PDF in the body.",
        }
      - {
          label: "Additional Files",
          name: "additional_files",
          widget: "file",
          required: false,
          media_library: { config: { multiple: true } },
          hint: "Use <Files frontMatter={frontMatter} /> to link the files in the body.",
        }
      - { name: slug, label: Slug, widget: string }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: imageUrl, label: ImageURL, widget: string }
  - name: dictionary
    label: "Hebrew Dictionary"
    files:
      - label: "Hebrew Dictionary"
        name: "dictionaryjson"
        file: "docusaurus/src/components/Hebrew/nonbinary-hebrew-dictionary.json"
        fields:
          - label: Translations
            name: translations
            widget: list
            add_to_top: true
            label_singular: "translation"
            summary: "{{lemma}} {{def}}"
            fields:
              - { label: Definition, name: def, widget: string }
              - { label: Lemma, name: lemma, widget: string }
