# This is the DecapCMS config file.
# https://decapcms.org/docs/intro/

backend:
  name: github
  branch: main
  repo: Nonbinary-Hebrew-Project/website

# These lines should *not* be indented
media_folder: "docusaurus/static/img"
public_folder: "/img/"

collections:
  - name: pages
    label: "Pages"
    folder: docusaurus/src/pages
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-line hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }

  - name: grammar
    label: "Grammar"
    folder: docusaurus/docs/grammar
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-line hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }
      - { name: slug, label: Slug, widget: string }
      - {
          name: sidebar_position,
          label: "Sidebar Position",
          widget: number,
          value_type: int,
        }

  - name: blog
    label: "NBHP In Practice"
    folder: docusaurus/blog
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-line hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }
      - {
          label: "PDF File",
          name: "pdf_file",
          widget: "file",
          required: false,
          media_library: { config: { multiple: false } },
          hint: "Only add PDF-type files. Use <PdfViewer frontMatter={frontMatter} /> to embed the PDF in the body.",
        }
      - {
          label: "Additional Files",
          name: "additional_files",
          widget: "file",
          required: false,
          media_library: { config: { multiple: true } },
          hint: "Use <Files frontMatter={frontMatter} /> to link the files in the body.",
        }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: imageUrl, label: ImageURL, widget: string }

  - name: resources
    label: "Resources"
    folder: docusaurus/docs/resources
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: "list"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - {
          name: body,
          hint: "For hebrew blocks, use <HB> צ </HB>. Multi-line hebrew blocks are not supported.",
          label: Body,
          widget: markdown,
        }
      - { name: slug, label: Slug, widget: string }
      - {
          name: sidebar_position,
          label: "Sidebar Position",
          widget: number,
          value_type: int,
        }

  - name: config
    label: "Configuration"
    files:
      - label: "Dropdowns"
        name: "dropdownconfig"
        file: "docusaurus/config/dropdowns.json"
        hint: "These determine the structure of the main nav bar."
        fields:
        - label: Dropdowns
          name: dropdowns
          widget: list
          label_singular: "dropdown"
          fields:
          - { name: label, label: "Dropdown Label", widget: string }
          - {
              name: items,
              label: Items,
              widget: "list",
              fields: [
                {name: "label", label: "label", widget: string},
                {name: "to", label: "to", widget: string},
              ]
            }
      - label: "Featured Content"
        name: "featuredcontentconfig"
        file: "docusaurus/config/featured-content.json"
        fields:
        - label: "Featured Items"
          name: "highlightedContent"
          widget: "list"
          label_singular: "Featured Item"
          hint: "These items will be displayed on the home page below the header content."
          fields:
          - { name: image, label: "Image", widget: "image" }
          - { name: headline, label: "Headline", widget: "string" }
          - { name: description, label: "Description", widget: "text" }
          - { name: ctaText, label: "Call to Action Text", widget: "string" }
          - { name: ctaLink, label: "Call to Action Link", widget: "string" }
      - label: "Homepage and Logo"
        name: "homepageheaderconfig"
        file: "docusaurus/config/homepage-header.json"
        fields:
        - { name: title, label: "Homepage Title", widget: string }
        - { name: subtitle, label: "Homepage Subtitle", widget: string }
        - { name: ctaText, label: "Call to Action Text", widget: string }
        - { name: ctaLink, label: "Call to Action Link", widget: string }
        - { name: heroImage, label: "Hero Image", widget: image }
        - { name: heroImageAlt, label: "Hero Image Alt Text", widget: string }
        - { name: siteTitle, label: "Site Title", hint: "Top left of the screen in the top bar", widget: string }
        - label: "Site Logo"
          name: "siteLogo"
          widget: "object"
          fields:
            - { name: src, label: "Logo Image", widget: image }
