backend:
  name: github
  branch: main
  repo: Nonbinary-Hebrew-Project/website

# These lines should *not* be indented
media_folder: "docusaurus/static/img"
public_folder: "/img/"

collections:
- name: docs
  label: "docs"
  folder: docusaurus/docs
  identifier_field: title
  extension: mdx
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
- name: blog
  label: "blog"
  folder: docusaurus/blog
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors"
      widget: "list"
      fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string }
        - { name: url, label: URL, widget: string }
        - { name: imageUrl, label: ImageURL, widget: string }