export const popularSchema = {
  ALEF: "",
  BET: "v",
  BET_DAGESH: "b",
  GIMEL: "g",
  DALET: "d",
  HE: "h",
  VAV: "v",
  ZAYIN: "z",
  HET: "ch",
  TET: "t",
  YOD: "y",
  KAF: "ch",
  KAF_DAGESH: "k",
  FINAL_KAF: "ch",
  LAMED: "l",
  MEM: "m",
  FINAL_MEM: "m",
  NUN: "n",
  FINAL_NUN: "n",
  SAMEKH: "s",
  AYIN: "'",
  PE: "f",
  PE_DAGESH: "p",
  FINAL_PE: "f",
  TSADI: "tz",
  FINAL_TSADI: "tz",
  QOF: "k",
  RESH: "r",
  SIN: "s",
  SHIN: "sh",
  TAV: "t",
  DAGESH: "",
  DAGESH_CHAZAQ: true,
  VOCAL_SHEVA: "'",
  PATAH: "a",
  HATAF_PATAH: "a",
  QAMATS: "a",
  HATAF_QAMATS: "a",
  SEGOL: "e",
  HATAF_SEGOL: "e",
  TSERE: "e",
  HIRIQ: "i",
  HOLAM: "o",
  HOLAM_HASER: "o",
  QUBUTS: "u",
  QAMATS_HE: "ah",
  SEGOL_HE: "eh",
  TSERE_HE: "eh",
  SEGOL_YOD: "ei",
  HIRIQ_YOD: "i",
  TSERE_YOD: "ei",
  FURTIVE_PATAH: "a",
  QAMATS_QATAN: "o",
  HOLAM_VAV: "o",
  SHUREQ: "u",
  MS_SUFX: "ayw",
  PASEQ: "",
  SOF_PASUQ: "",
  MAQAF: "-",
  DIVINE_NAME: "Yah",
  DIVINE_NAME_ELOHIM: "Elohim",
  ADDITIONAL_FEATURES: [
      {
          FEATURE: "cluster",
          HEBREW: "\u{05E9}\u{05C1}\u{05BC}",
          TRANSLITERATION: "sh"
      },
      {
          FEATURE: "cluster",
          HEBREW: "ײַ",
          TRANSLITERATION: "Yah"
      },
      {
          FEATURE: "cluster",
          HEBREW: "\u{05E6}\u{05BC}",
          TRANSLITERATION: "tz"
      },
  ],
  longVowels: true,
  shevaAfterMeteg: true,
  sqnmlvy: true,
  qametsQatan: false,
  wawShureq: true,
  article: true,
  allowNoNiqqud: true,
  strict: false,
  holemHaser: "remove"
};
